version: "3.5"
  
services:
  workflow-engine:
    image: pkalkman/mve-workflowengine:0.4.6
    environment:
      AUTH_DOMAIN: /run/secrets/AUTH_DOMAIN
      AUTH_SECRET: /run/secrets/AUTH_SECRET
      STORAGE_HOST: /run/secrets/STORAGE_HOST
      HOST: 0.0.0.0
      HTTP_PORT: 8181
      LOG_LEVEL: 1
  workflow-database:
    image: 'mongo:4.0.14'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mveroot
      - MONGO_INITDB_ROOT_PASSWORD=2020minivideoencoder!
      - MONGO_INITDB_DATABASE=workflow-db
    volumes:
      - ./WorkflowDatabase/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mve-workflow-database:/data.db
    ports:
      - '27017:27017'
secrets:
  AUTH_DOMAIN:
    external: true
  AUTH_SECRET:
    external: true
  STORAGE_HOST:
    external: true
volumes:
  workflow-database-volume:
    external: true