version: '2'
services:
  workflowdb:
    image: 'mongo:4.0.14'
    container_name: 'workflow-db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mveroot
      - MONGO_INITDB_ROOT_PASSWORD=2020minivideoencoder!
      - MONGO_INITDB_DATABASE=workflow-db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/workflow-db.db:/data.db
    ports:
      - '27017:27017'
    networks: 
      - mve-network
networks:
    mve-network: